"""Module Storing Data Used for Populating Visualizations."""

import pandas as pd

# For Education Graph
fau_data: list[str] = [
    "BA in Interdisciplinary Mathematical Sciences (Honors)",
    "Focus Path <br> in Biochemistry",
    "Magna Cum Laude",
    "Recipient of Outstanding <br> Thesis Award",
    "Graduated: May 2023",
    "Mathematics Tutor <br> for 2 Years",
    "Computational Chemistry <br> Lab Volunteer",
]
tdi_data: list[str] = [
    "Data Scientist Certification",
    "The Data Incubator <br> Fellowship Program",
    "Graduated: Nov 2023",
    "Achieved > 90% <br> on all Assignments",
    "Capstone Project: <br> Ingredient Identifier",
]

# For Intern Graph
intern_data: dict[str, str] = {
    "company": "24/7 Software",
    "role": "Buisiness Analyst Intern",
    "timeframe": "May 2022 - May 2023",
    "project": "Spatiotemporal Determinants of Football Stadium Incidents",
    "project_desc1": "Initiated analysis of raw Stadium Incident Data (>1G) <br> reported at one professional football stadium with <br> the goal to quantitatively analyze stadium incident response times <br> and predict incidents' occurrence and locations. <br> Regularly presented work to senior leadership and extended initial <br> analysis and modeling to include 20 professional sports stadiums.",
    "project_desc2": "Cleaned and processed the data, built regression <br> models, and performed classification using Apriori Association Rules Mining (ARM) <br> to analyze the spatiotemporal determinants of football stadium incidents.",
    "project_desc3": "Constructed visualizations displaying the likelihood of incidents <br> occurring in various stadium locations during various times",
    "project_desc4": "Results elucidated operational inefficiencies particularly <br> related to security incidents and ADA accessibility requests.",
    "results_1": "25.6% of accessibility requests occurred when the stadium gates opened.",
    "results_2": "9% of fan code of conduct violations occurred <br> in a specific section of the stadium during the 2nd quarter.",
    "project impact": "Verified that data driven insights could be productionalized <br> and introduced a model capable of productionalization. <br> Currently, the company is developing a product <br> that would improve venue operations based on time/location risk prediction.",
}

# Positions for Intern Graph
intern_positions: dict[str, tuple[int | float, int]] = {
    "company": (0, 10),
    "role": (-1, 7),
    "timeframe": (1, 7),
    "project": (0, 4),
    "project_desc1": (-2, 1),
    "project_desc2": (-1, 1),
    "project_desc3": (1, 1),
    "project_desc4": (2, 1),
    "results_1": (-0.5, -2),
    "results_2": (0.5, -2),
    "project impact": (0, -5),
}

# This needs to be implemented in a way that enables easier modification and recreation
# Skills DataFrame
skills_data = pd.DataFrame(
    {
        "skill": {
            0: "Time-series <br> Analysis",
            1: "Association Rules <br>  Mining",
            2: "NLP",
            3: "Tensorflow",
            4: "Deep Learning",
            5: "Random Forest",
            6: "K-means",
            7: "Gradient Descent",
            8: "Neural Networks",
            9: "Supervised <br> Learning",
            10: "Unsupervised <br> Learning",
            11: "pySpark",
            12: "SQL",
            13: "Text <br> Classification",
            14: "Hyperparameter <br> Tuning",
            15: "Feature <br> Selection",
            16: "PCA",
            17: "XML",
            18: "HTML",
            19: "Scikit-Learn",
            20: "Plotly",
            21: "Altair",
            22: "Streamlit",
            23: "Seaborn",
            24: "Pipeline Architecture",
            25: "Linear Algebra",
            26: "sqlalchemy",
            27: "nltk",
            28: "Social Graphs",
            29: "Image <br> Processing",
            30: "Data <br> Ingestion",
            31: "Python",
            32: "Bash",
            33: "R",
            34: "Scala",
            35: "Mathematical <br> Modeling",
            36: "Probability Theory",
            37: "Probalistic Models",
            38: "Data Cleaning",
            39: "Data Processing",
            40: "Data Visualization",
            41: "Statistical <br> Analysis",
            42: "Regex",
            43: "Text Processing",
            44: "Data Mining",
            45: "Markdown",
            46: "LaTeX",
            47: "Jupyter <br> Notebooks",
            48: "Algorithm <br> Developement",
            49: "Sports <br> Analytics",
            50: "Operations <br> Management",
            51: "Presentations",
            52: "Communication at <br> all Levels",
            53: "ML Operations",
            54: "Excel",
            55: "Data Analytics",
            56: "Git",
        },
        "type": {
            0: "Data Science <br> and <br> Machine Learning",
            1: "Data Science <br> and <br> Machine Learning",
            2: "Data Science <br> and <br> Machine Learning",
            3: "Data Science <br> and <br> Machine Learning",
            4: "Data Science <br> and <br> Machine Learning",
            5: "Data Science <br> and <br> Machine Learning",
            6: "Data Science <br> and <br> Machine Learning",
            7: "Data Science <br> and <br> Machine Learning",
            8: "Data Science <br> and <br> Machine Learning",
            9: "Data Science <br> and <br> Machine Learning",
            10: "Data Science <br> and <br> Machine Learning",
            11: "Data Science <br> and <br> Machine Learning",
            12: "Data Science <br> and <br> Machine Learning",
            13: "Data Science <br> and <br> Machine Learning",
            14: "Data Science <br> and <br> Machine Learning",
            15: "Data Science <br> and <br> Machine Learning",
            16: "Data Science <br> and <br> Machine Learning",
            17: "Data Science <br> and <br> Machine Learning",
            18: "Data Science <br> and <br> Machine Learning",
            19: "Data Science <br> and <br> Machine Learning",
            20: "Data Science <br> and <br> Machine Learning",
            21: "Data Science <br> and <br> Machine Learning",
            22: "Data Science <br> and <br> Machine Learning",
            23: "Data Science <br> and <br> Machine Learning",
            24: "Data Science <br> and <br> Machine Learning",
            25: "Data Science <br> and <br> Machine Learning",
            26: "Data Science <br> and <br> Machine Learning",
            27: "Data Science <br> and <br> Machine Learning",
            28: "Data Science <br> and <br> Machine Learning",
            29: "Data Science <br> and <br> Machine Learning",
            30: "Data Science <br> and <br> Machine Learning",
            31: "Programming",
            32: "Programming",
            33: "Programming",
            34: "Programming",
            35: "Industry <br> Experience",
            36: "Industry <br> Experience",
            37: "Industry <br> Experience",
            38: "Industry <br> Experience",
            39: "Industry <br> Experience",
            40: "Industry <br> Experience",
            41: "Industry <br> Experience",
            42: "Industry <br> Experience",
            43: "Industry <br> Experience",
            44: "Industry <br> Experience",
            45: "Industry <br> Experience",
            46: "Industry <br> Experience",
            47: "Industry <br> Experience",
            48: "Industry <br> Experience",
            49: "Industry <br> Experience",
            50: "Industry <br> Experience",
            51: "Industry <br> Experience",
            52: "Industry <br> Experience",
            53: "Industry <br> Experience",
            54: "Industry <br> Experience",
            55: "Industry <br> Experience",
            56: "Industry <br> Experience",
        },
        "value": {
            0: 5,
            1: 5,
            2: 5,
            3: 5,
            4: 5,
            5: 5,
            6: 5,
            7: 5,
            8: 5,
            9: 5,
            10: 5,
            11: 5,
            12: 5,
            13: 5,
            14: 5,
            15: 5,
            16: 5,
            17: 5,
            18: 5,
            19: 5,
            20: 5,
            21: 5,
            22: 5,
            23: 5,
            24: 5,
            25: 5,
            26: 5,
            27: 5,
            28: 5,
            29: 5,
            30: 5,
            31: 5,
            32: 5,
            33: 5,
            34: 5,
            35: 5,
            36: 5,
            37: 5,
            38: 5,
            39: 5,
            40: 5,
            41: 5,
            42: 5,
            43: 5,
            44: 5,
            45: 5,
            46: 5,
            47: 5,
            48: 5,
            49: 5,
            50: 5,
            51: 5,
            52: 5,
            53: 5,
            54: 5,
            55: 5,
            56: 5,
        },
        "category": {
            0: "Data Science",
            1: "Machine <br> Learning",
            2: "Machine <br> Learning",
            3: "Machine <br> Learning",
            4: "Machine <br> Learning",
            5: "Machine <br> Learning",
            6: "Machine <br> Learning",
            7: "Machine <br> Learning",
            8: "Machine <br> Learning",
            9: "Machine <br> Learning",
            10: "Machine <br> Learning",
            11: "Data Science",
            12: "Data Science",
            13: "Machine <br> Learning",
            14: "Machine <br> Learning",
            15: "Machine <br> Learning",
            16: "Data Science",
            17: "Data Science",
            18: "Data Science",
            19: "Machine <br> Learning",
            20: "Data Science",
            21: "Data Science",
            22: "Data Science",
            23: "Data Science",
            24: "Machine <br> Learning",
            25: "Machine <br> Learning",
            26: "Data Science",
            27: "Machine <br> Learning",
            28: "Data Science",
            29: "Machine <br> Learning",
            30: "Data Science",
            31: "Languages",
            32: "Languages",
            33: "Languages",
            34: "Languages",
            35: "Industry Skills",
            36: "Industry Skills",
            37: "Industry Skills",
            38: "Industry Skills",
            39: "Industry Skills",
            40: "Industry Skills",
            41: "Industry Skills",
            42: "Industry Skills",
            43: "Industry Skills",
            44: "Industry Skills",
            45: "Technologies",
            46: "Technologies",
            47: "Technologies",
            48: "Industry Skills",
            49: "Industry Skills",
            50: "Industry Skills",
            51: "Social Skills",
            52: "Social Skills",
            53: "Industry Skills",
            54: "Technologies",
            55: "Industry Skills",
            56: "Technologies",
        },
    }
)
